### ISSUE TITLE
Booking Page

### ISSUE THREAD

**Issue by fjinfanteprofile** [fjinfanteprofile/FranOnWheels-front#22]
* [ ] [Booking Page Mockup](https://github.com/fjinfanteprofile/FranOnWheels/issues/16)
* [ ] [Booking Page Functionality](https://github.com/fjinfanteprofile/FranOnWheels/issues/17)
* [ ] [Booking Page Redirections](https://github.com/fjinfanteprofile/FranOnWheels/issues/18)
