### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by fjinfanteprofile** [fjinfanteprofile/FranOnWheels-front#24]
Main page must contain
* [ ]   [Main Page Mockup](https://github.com/fjinfanteprofile/FranOnWheels/issues/12)
* [ ]   [Booking page access](https://github.com/fjinfanteprofile/FranOnWheels/issues/8)
* [ ]   [View User profile](https://github.com/fjinfanteprofile/FranOnWheels/issues/9)
* [ ]   [User-friendly interface](https://github.com/fjinfanteprofile/FranOnWheels/issues/13)
